version: '3.8'
services:
  neo4j:
    image: neo4j:5.10
    container_name: global-wsp
    environment:
      - NEO4J_AUTH=neo4j/pass12345
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
